### ISSUE TITLE
Create Docked Left Nav

### ISSUE THREAD

**Issue by JPG1101** [impactlab/oeem-client#30]
[http://www.material-ui.com/#/components/left-nav](url)
- Using "Docked Example" from link above
- Spans columns 1 & 2
- Depth of 16dp: additional notes on depth as outlined by Material Design guidelines listed [here](https://www.google.com/design/spec/what-is-material/elevation-shadows.html#elevation-shadows-elevation-android-)

![Uploading OEE_DockedLeftNav.jpg…]()

**Comment by hunterowens** [comment]
:+1: :tada: to @JPG1101's first github issue
