### ISSUE TITLE
Add combined electricity/gas tab to show total savings and usage

### ISSUE THREAD

**Issue by philngo** [impactlab/oeem-client#4]
Tab should have the label "All energy types", and should show in total kWh (converting from therms if necessary):
- [x] the timeseries of monthly project savings available on the electricity and gas tabs
- [x] the quick stats with annual usage and annual savings numbers
- [ ] relevant project histograms (percent savings, gross savings, and annual savings.)

**Comment by cathydeng** [comment]
in progress in the ui-updates branch
